### ISSUE TITLE
Output base 64

### ISSUE THREAD

**Issue by mongveasna** [bamlab/react-native-image-resizer#118]
Hi guys,

Can we output image as base64

thanks,

**Comment by baskan** [comment]
also input from base64 would be super nice.

**Comment by mistenkt** [comment]
@baskan Input from base64 already works.

**Comment by greenais** [comment]
Any ideas if base64 output is possible, still?

**Comment by diby3ndu** [comment]
I think this feature would be essential as we need to depend on other modules like `react-native-fs` in order to convert to base64. But that should be provided out of the box

**Comment by greenais** [comment]
And this (to my understanding) shouldn't be too hard to implement - as soon as we have result image object somewhere inside before dropping it to fs - just image.encode(base64) and expose result through API... I'm not native coder at all, so it's just my assumptions, but from JS side I'm ready to help/test adding this.

**Comment by greenais** [comment]
Any progress assumptions on this enchancement, perhaps?

**Comment by 4ian** [comment]
I'm not actively needing this feature so not working on this. Happy to accept PR for this though :)

**Comment by pstanton** [comment]
damn it, i only started playing with this project because I misread the docs and thought this was implemented :(

**Comment by pstanton** [comment]
@4ian how would you like to design the API to achieve this? The implementation is not difficult on android. Just not sure what your preference is...

**Comment by pstanton** [comment]
@4ian I implemented it locally (on 1.0.0) only to realise that master has some changes so i'll have to merge a bit. But ... I found it easy to implement by having ImageResizer receive the response map as a parameter and populate it directly rather than returning a File (or base64 String). This allowed me to fork logic without changing the return type AND to populate the response with more attributes (such as resultant width/height).
Does this sound like a change that would accept?

**Comment by 4ian** [comment]
I would accept such a change, but I think we should transition to have as parameters an object `options`, so it's easier to add optional options in the future :) (instead of having this long list of parameters for which some are nullable).

This will be a breaking change but it's no problem (will just release this as version 2.0.0) and it will be much better for the future.

> to populate the response with more attributes (such as resultant width/height).

No problem for doing this too.

**Comment by pstanton** [comment]
Ok i'll apply my modifications to a fork of master tomorrow and you can review.

Parameters as options makes sense for the javascript layer - would you continue that on in the java/ObjC world? (ie use a map) I'll not make this change since it is not required to achieve what I'm doing and impacts more of your codebase, but agree it is a good idea.

**Comment by 4ian** [comment]
Yes, I think it's perfectly ok to do this change only on the JavaScript interface :)

**Comment by pstanton** [comment]
if someone can do the same for iOS that would be (y) good!

**Comment by pstanton** [comment]
@4ian any plans to integrate this PR and/or implement the iOS side?

**Comment by 4ian** [comment]
I'm not actively using the module right now so I don't have any plan to do it myself :/
I would like to keep feature parity between Android and IOS, so having the iOS side implemented would  awesome though.

**Comment by pstanton** [comment]
if anyone would like to implement the same as my patch above for iOS we would be willing to pay for your time. contact me if interested.

**Comment by alexandrzavalii** [comment]
@pstanton 
Contact me if you are still interested in the implementation.

**Comment by alexanderkho** [comment]
As [this answer](https://stackoverflow.com/questions/41171702/react-native-resize-image-and-convert-to-base64) points out, you can use react-native-fs to convert the outputted image to Base64. 

```
handleBase64 = async (path) => {
  const resizedImage = await ImageResizer.createResizedImage(path, 200, 80, 'JPEG', 80, 0, RNFS.DocumentDirectoryPath);
  const base64 = await RNFS.readFile(resizedImage.uri, 'base64');
  return base64;
}
```
