### ISSUE TITLE
Arithmetic Exception - divide by zero

### ISSUE THREAD

**Issue by jahicDario** [bamlab/react-native-image-resizer#186]
I am getting this error when I try to resize image on Samsung S6 and S6 edge.
![Screenshot_20190715-142051](https://user-images.githubusercontent.com/17848628/61218427-4aeff300-a712-11e9-934a-3b43835c06db.png)

**Comment by bneigher** [comment]
me too

**Comment by PierreCapo** [comment]
@jahicDario Do you know if this also happens on most recent samsung (S8/S9/S10) ?

**Comment by AdrianBordeianu** [comment]
Any updates in here?

**Comment by AdrianBordeianu** [comment]
This happens because when you get the photos using CameraRoll or another library, you specifically have to include imageSize and get the width and height in the result. I'm using the libraries like this:

`CameraRoll.getPhotos({ first: 100, include: ['imageSize'] })
      .then((photo: PhotoIdentifiersPage) => {
        if (isLoading) {
          setIsLoading(false);
        }
        let imagesMap: IGalleryImage[] = [];
        photo.edges.map((edge: PhotoIdentifier, index: number) => {
          imagesMap = [ ...imagesMap, edge.node.image];
        });`

`ImageResizer.createResizedImage(
    item.uri,
    item.width - IMAGE_SHRINK_VALUE,
    item.height - IMAGE_SHRINK_VALUE,
    'JPEG',
    50
  )
  .then((response) => {`
